=== aspectran/aspectran/core/src/main/resources/com/aspectran/core/context/rule/parser/xml/dtd/aspectran-9.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
  XML DTD for the Aspectran Configuration File, Version 9.0

  Copyright 2018-present The Aspectran Project

  This DTD module is identified by the PUBLIC and SYSTEM identifiers:

  PUBLIC "-//ASPECTRAN//DTD Aspectran 9.0//EN"
  SYSTEM "https://aspectran.com/dtd/aspectran-9.dtd">

  XML documents that conform to this DTD should declare the following doctype:

  <!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran 9.0//EN"
          "https://aspectran.com/dtd/aspectran-9.dtd">
-->

<!ELEMENT aspectran (
  description*,
  settings?,
  (typeAliases | environment | aspect | bean | schedule | translet | template | append)*
)>

<!ELEMENT description (#PCDATA)>
<!ATTLIST description
  profile CDATA #IMPLIED
  style   (apon | compact | compressed) #IMPLIED
>

<!ELEMENT settings (setting+)>
<!ELEMENT setting EMPTY>
<!ATTLIST setting
  name    CDATA #REQUIRED
  value   CDATA #REQUIRED
>

<!ELEMENT typeAliases (typeAlias+)>
<!ELEMENT typeAlias EMPTY>
<!ATTLIST typeAlias
  alias   CDATA #REQUIRED
  type    CDATA #REQUIRED
>

<!ELEMENT environment (description*, property*, properties*)>
<!ATTLIST environment
  profile CDATA #IMPLIED
>

<!ELEMENT aspect (description*, joinpoint?, settings?, advice?, exception?)>
<!ATTLIST aspect
  id       ID #IMPLIED
  order    CDATA #IMPLIED
  isolated (true | false) #IMPLIED
  disabled (true | false) #IMPLIED
>

<!ELEMENT joinpoint (#PCDATA)>
<!ATTLIST joinpoint
  target  (activity | method) #IMPLIED
>

<!ELEMENT advice (before?, after?, finally?)>
<!ATTLIST advice
  bean    CDATA #IMPLIED
>

<!ELEMENT before  (headers | echo | (action | invoke))>
<!ELEMENT after   (headers | echo | (action | invoke))>
<!ELEMENT finally (thrown?, (headers | echo | (action | invoke)))>

<!ELEMENT exception (description*, thrown+)>

<!ELEMENT thrown ((headers | echo | (action | invoke)?)?, (transform | dispatch | redirect)*)>
<!ATTLIST thrown
  type    CDATA #IMPLIED
>

<!ELEMENT bean (description*, filter?, argument*, arguments*, property*, properties*)>
<!ATTLIST bean
  id            CDATA #IMPLIED
  class         CDATA #IMPLIED
  scan          CDATA #IMPLIED
  mask          CDATA #IMPLIED
  factoryBean   CDATA #IMPLIED
  factoryMethod CDATA #IMPLIED
  initMethod    CDATA #IMPLIED
  destroyMethod CDATA #IMPLIED
  dependsOn     CDATA #IMPLIED
  scope         (singleton | prototype | request | session) #IMPLIED
  singleton     (true | false) #IMPLIED
  lazyInit      (true | false) #IMPLIED
  lazyDestroy   (true | false) #IMPLIED
  important     (true | false) #IMPLIED
>

<!ELEMENT filter (#PCDATA)>
<!ATTLIST filter
  class   CDATA #IMPLIED
>

<!ELEMENT schedule (description*, scheduler, job*)>
<!ATTLIST schedule
  id       ID #IMPLIED
  isolated (true | false) #IMPLIED
  disabled (true | false) #IMPLIED
>

<!ELEMENT scheduler (trigger)>
<!ATTLIST scheduler
  bean    CDATA #IMPLIED
>

<!ELEMENT trigger (#PCDATA)>
<!ATTLIST trigger
  type    CDATA #IMPLIED
>

<!ELEMENT job EMPTY>
<!ATTLIST job
  translet CDATA #REQUIRED
  isolated (true | false) #IMPLIED
  disabled (true | false) #IMPLIED
>

<!ELEMENT translet (
  description*,
  (request? | (parameter*, parameters*, attribute*, attributes*)),
  ((contents | content)? | (choose | headers | echo | action | include)*),
  (response* | (transform | dispatch | forward | redirect)?),
  exception?
)>
<!ATTLIST translet
  name    CDATA #REQUIRED
  scan    CDATA #IMPLIED
  mask    CDATA #IMPLIED
  method  CDATA #IMPLIED
  async   (true | false) #IMPLIED
  timeout CDATA #IMPLIED
>

<!ELEMENT request (parameter*, attribute*, parameters*, attributes*)>
<!ATTLIST request
  method   CDATA #IMPLIED
  encoding CDATA #IMPLIED
>

<!ELEMENT contents (content*)>
<!ATTLIST contents
  name    CDATA #IMPLIED
>

<!ELEMENT content (choose | headers | echo | action | include)*>
<!ATTLIST content
  name    CDATA #IMPLIED
>

<!ELEMENT choose (when*, otherwise?)>

<!ELEMENT when ((headers | echo | action | include | choose)*, (transform | dispatch | forward | redirect)?)>
<!ATTLIST when
  test    CDATA #IMPLIED
>

<!ELEMENT otherwise ((headers | echo | action | include | choose)*, (transform | dispatch | forward | redirect)?)>

<!ELEMENT headers (item*)>
<!ATTLIST headers
  id      CDATA #IMPLIED
  hidden  (true | false) #IMPLIED
>

<!ELEMENT echo (item*)>
<!ATTLIST echo
  id      CDATA #IMPLIED
  hidden  (true | false) #IMPLIED
>

<!ELEMENT action (argument*, arguments*, property*, properties*)>
<!ATTLIST action
  id      CDATA #IMPLIED
  bean    CDATA #REQUIRED
  method  CDATA #REQUIRED
  hidden  (true | false) #IMPLIED
>

<!ELEMENT invoke (argument*, arguments*, property*, properties*)>
<!ATTLIST invoke
  method  CDATA #REQUIRED
  hidden  (true | false) #IMPLIED
>

<!ELEMENT include (parameter*, parameters*, attribute*, attributes*)>
<!ATTLIST include
  id       CDATA #IMPLIED
  translet CDATA #REQUIRED
  method   CDATA #IMPLIED
  hidden   (true | false) #IMPLIED
>

<!ELEMENT response ((choose | headers | echo | action | include)*, (transform | dispatch | forward | redirect)?)>
<!ATTLIST response
  name     CDATA #IMPLIED
  encoding CDATA #IMPLIED
>

<!ELEMENT transform (template?)>
<!ATTLIST transform
  format      CDATA #IMPLIED
  contentType CDATA #IMPLIED
  encoding    CDATA #IMPLIED
  default     (true | false) #IMPLIED
  pretty      (true | false) #IMPLIED
>

<!ELEMENT dispatch EMPTY>
<!ATTLIST dispatch
  name        CDATA #REQUIRED
  dispatcher  CDATA #IMPLIED
  contentType CDATA #IMPLIED
  encoding    CDATA #IMPLIED
  default     (true | false) #IMPLIED
>

<!ELEMENT forward (attribute*, attributes*)>
<!ATTLIST forward
  contentType CDATA #IMPLIED
  translet    CDATA #REQUIRED
  method      CDATA #IMPLIED
  default     (true | false) #IMPLIED
>

<!ELEMENT redirect (parameter*, parameters*)>
<!ATTLIST redirect
  contentType            CDATA #IMPLIED
  path                   CDATA #REQUIRED
  encoding               CDATA #IMPLIED
  excludeNullParameters  (true | false) #IMPLIED
  excludeEmptyParameters (true | false) #IMPLIED
  default                (true | false) #IMPLIED
>

<!ELEMENT parameters (item*)>
<!ATTLIST parameters
  profile CDATA #IMPLIED
>

<!ELEMENT attributes (item*)>
<!ATTLIST attributes
  profile CDATA #IMPLIED
>

<!ELEMENT arguments (item*)>
<!ATTLIST arguments
  profile CDATA #IMPLIED
>

<!ELEMENT properties (item*)>
<!ATTLIST properties
  profile CDATA #IMPLIED
>

<!ELEMENT item (#PCDATA | value | entry | bean)*>
<!ATTLIST item
  type      (single | array | list | map | set | properties) #IMPLIED
  name      CDATA #IMPLIED
  value     CDATA #IMPLIED
  valueType (string | int | long | float | double | boolean | parameters | file | multipart-file | bean) #IMPLIED
  tokenize  (true | false) #IMPLIED
  mandatory (true | false) #IMPLIED
  secret    (true | false) #IMPLIED
>

<!ELEMENT parameter (#PCDATA | value | entry | bean)*>
<!ATTLIST parameter
  type      (single | array | list | map | set | properties) #IMPLIED
  name      CDATA #IMPLIED
  value     CDATA #IMPLIED
  valueType (string | int | long | float | double | boolean | parameters | file | multipart-file | bean) #IMPLIED
  tokenize  (true | false) #IMPLIED
  mandatory (true | false) #IMPLIED
  secret    (true | false) #IMPLIED
>

<!ELEMENT attribute (#PCDATA | value | entry | bean)*>
<!ATTLIST attribute
  type      (single | array | list | map | set | properties) #IMPLIED
  name      CDATA #IMPLIED
  value     CDATA #IMPLIED
  valueType (string | int | long | float | double | boolean | parameters | file | multipart-file | bean) #IMPLIED
  tokenize  (true | false) #IMPLIED
  mandatory (true | false) #IMPLIED
  secret    (true | false) #IMPLIED
>

<!ELEMENT argument (#PCDATA | value | entry | bean)*>
<!ATTLIST argument
  type      (single | array | list | map | set | properties) #IMPLIED
  name      CDATA #IMPLIED
  value     CDATA #IMPLIED
  valueType (string | int | long | float | double | boolean | parameters | file | multipart-file | bean) #IMPLIED
  tokenize  (true | false) #IMPLIED
>

<!ELEMENT property (#PCDATA | value | entry | bean)*>
<!ATTLIST property
  type      (single | array | list | map | set | properties) #IMPLIED
  name      CDATA #IMPLIED
  value     CDATA #IMPLIED
  valueType (string | int | long | float | double | boolean | parameters | file | multipart-file | bean) #IMPLIED
  tokenize  (true | false) #IMPLIED
>

<!ELEMENT value (#PCDATA)>

<!ELEMENT entry (#PCDATA | bean)*>
<!ATTLIST entry
  name     CDATA #IMPLIED
  value    CDATA #IMPLIED
  tokenize (true | false) #IMPLIED
>

<!ELEMENT template (#PCDATA)>
<!ATTLIST template
  id          CDATA #IMPLIED
  engine      CDATA #IMPLIED
  name        CDATA #IMPLIED
  file        CDATA #IMPLIED
  resource    CDATA #IMPLIED
  url         CDATA #IMPLIED
  style       (apon | compact | compressed) #IMPLIED
  contentType CDATA #IMPLIED
  encoding    CDATA #IMPLIED
  noCache     (true | false) #IMPLIED
>

<!ELEMENT append (
  description*,
  settings?,
  (typeAliases | environment | aspect | bean | schedule | translet | template)*
)>
<!ATTLIST append
  file     CDATA #IMPLIED
  resource CDATA #IMPLIED
  url      CDATA #IMPLIED
  format   (xml | apon) #IMPLIED
  profile  CDATA #IMPLIED
>

=== aspectran/aspectran/demo/src/main/resources/com/aspectran/demo/skylark/skylark.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran 9.0//EN"
        "https://aspectran.com/dtd/aspectran-9.dtd">
<aspectran>

    <description>
        Skylark is a text-to-speech web application.
    </description>

    <settings>
        <setting name="transletNamePrefix" value="/skylark"/>
    </settings>

    <translet name="/">
        <echo id="page">
            <item name="headline">Skylark Terminal</item>
            <item name="teaser">Skylark is a text to speech program that converts any written text into spoken words.</item>
            <item name="include">skylark/skylark</item>
            <item name="style">plate</item>
        </echo>
        <dispatch name="templates/default"/>
    </translet>

    <append resource="com/aspectran/demo/skylark/tts/voices.xml"/>
    <append resource="com/aspectran/demo/skylark/tts/api-v0.xml"/>

</aspectran>

=== aspectran/aspectran/demo/src/main/resources/com/aspectran/demo/home/main.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran 9.0//EN"
        "https://aspectran.com/dtd/aspectran-9.dtd">
<aspectran>

    <translet name="/">
        <echo id="page">
            <item name="headline">Welcome to Aspectran Demo Site</item>
            <item name="subheadline">Recommended best practices developed with Aspectran</item>
            <item name="teaser">This is a site to demonstrate examples developed using Aspectran.</item>
            <item name="include">home/main</item>
            <item name="style">plate solid</item>
        </echo>
        <dispatch name="templates/default"/>
    </translet>

</aspectran>

=== aspectran/aspectran/core/src/test/resources/config/bean/call/bean-call-test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran 9.0//EN"
        "https://aspectran.com/dtd/aspectran-9.dtd">
<aspectran>

    <description>
        This is an Aspectran configuration for testing bean calls.
    </description>

    <bean id="firstBean" class="com.aspectran.core.sample.call.FirstBean"/>
    <bean id="secondBean" class="com.aspectran.core.sample.call.SecondBean"/>
    <bean id="thirdBean" class="com.aspectran.core.sample.call.ThirdBean"/>

    <bean id="totalBean" class="com.aspectran.core.sample.call.TotalBean">
        <property name="orderedBeans1" type="array">
            <value>#{firstBean}</value>
            <value>#{secondBean}</value>
            <value>#{thirdBean}</value>
        </property>
        <property name="orderedBeans2" type="array">
            <value>#{firstBean}</value>
            <value>#{secondBean}</value>
            <value>#{thirdBean}</value>
        </property>
    </bean>

</aspectran>

=== aspectran/aspectran/with-mybatis/src/test/resources/com/aspectran/mybatis/test/test-context.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran 9.0//EN"
        "https://aspectran.com/dtd/aspectran-9.dtd">
<aspectran>

    <!-- Test SqlSessionAgent with single transaction -->
    <bean id="singleSqlSession" class="com.aspectran.mybatis.DefaultSqlSessionAgent">
        <argument>singleTxAspect</argument>
        <property name="targetBeanId">singleSqlSession</property>
        <property name="sqlSessionFactoryBeanId">sqlSessionFactory</property>
    </bean>

    <bean id="singleSqlMapperProvider" class="com.aspectran.mybatis.test.mapper.TestSqlMapperProvider">
        <argument>#{singleSqlSession}</argument>
    </bean>

    <bean id="singleDao" class="com.aspectran.mybatis.test.dao.TestDao">
        <argument>#{singleSqlMapperProvider}</argument>
    </bean>

    <!-- Read-Only session: single transaction -->
    <bean id="readOnlySqlSession" class="com.aspectran.mybatis.DefaultSqlSessionAgent">
        <argument>readOnlyTxAspect</argument>
        <property name="targetBeanId">readOnlySqlSession</property>
        <property name="sqlSessionFactoryBeanId">sqlSessionFactory</property>
        <property name="readOnly" valueType="boolean">true</property>
        <property name="readOnlyRollbackOnClose" valueType="boolean">true</property>
    </bean>

    <bean id="readOnlySqlMapperProvider" class="com.aspectran.mybatis.test.mapper.TestSqlMapperProvider">
        <argument>#{readOnlySqlSession}</argument>
    </bean>

    <bean id="readOnlyDao" class="com.aspectran.mybatis.test.dao.TestDao">
        <argument>#{readOnlySqlMapperProvider}</argument>
    </bean>

    <!-- Test SqlSessionAgent with SERIALIZABLE isolation level -->
    <bean id="serializableSqlSession" class="com.aspectran.mybatis.DefaultSqlSessionAgent">
        <argument>serializableTxAspect</argument>
        <property name="targetBeanId" value="serializableSqlSession"/>
        <property name="sqlSessionFactoryBeanId" value="sqlSessionFactory"/>
        <property name="isolationLevelAsString" value="SERIALIZABLE"/>
    </bean>

    <bean id="serializableSqlMapperProvider" class="com.aspectran.mybatis.test.mapper.TestSqlMapperProvider">
        <argument>#{serializableSqlSession}</argument>
    </bean>

    <bean id="serializableDao" class="com.aspectran.mybatis.test.dao.TestDao">
        <argument>#{serializableSqlMapperProvider}</argument>
    </bean>

</aspectran>

=== aspectran/aspectran/with-netty/src/test/resources/config/aspectran-rules.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran 9.0//EN"
        "https://aspectran.com/dtd/aspectran-9.dtd">
<aspectran>

    <description>
        Test configuration for Netty server integration.
    </description>

    <append resource="config/netty/netty-server.xml"/>

    <translet name="/hello">
        <echo>
            <item name="message">Hello Netty World!</item>
        </echo>
        <transform format="json"/>
    </translet>

    <translet name="/echo" method="POST">
        <transform format="text">
            <template>Echo: ${msg}</template>
        </transform>
    </translet>

    <translet name="/session">
        <action bean="testSessionBean" method="process"/>
        <transform format="json"/>
    </translet>

    <translet name="/virtual-thread">
        <action bean="testSessionBean" method="checkVirtualThread"/>
        <transform format="json"/>
    </translet>

    <translet name="/redirect">
        <redirect path="/hello?referrer=/"/>
    </translet>

    <bean id="testSessionBean" class="com.aspectran.netty.server.TestSessionBean"/>

</aspectran>

=== aspectran/aspectran/core/src/test/resources/com/aspectran/core/context/rule/appender/scoped-override-valid.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran 9.0//EN"
        "https://aspectran.com/dtd/aspectran-9.dtd">
<aspectran>
    <append resource="com/aspectran/core/context/rule/appender/scoped-override-target.xml">
        <typeAliases>
            <typeAlias alias="myAlias" type="java.lang.StringBuilder"/>
        </typeAliases>

        <environment>
            <property name="app.title">Overridden Title</property>
        </environment>

        <bean id="testBean" class="com.aspectran.core.context.rule.appender.ScopedOverrideTest$TestBean">
            <property name="message">Overridden Message</property>
        </bean>

        <translet name="/hello">
            <echo>
                <item name="msg">Overridden Hello</item>
            </echo>
        </translet>
    </append>
</aspectran>

=== aspectran/aspectran/with-undertow/src/test/resources/config/undertow/tow-controller.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran 9.0//EN"
        "https://aspectran.com/dtd/aspectran-9.dtd">
<aspectran>

    <description>
        A collection of commands for controlling the Embedded Undertow Server.
    </description>

    <translet name="undertow">
        <description style="apon">
            |
            |{{underline}}To control Undertow, try one of the following commands:{{reset}}
            |   {{CYAN}}undertow start{{reset}}  Runs an Undertow Server
            |   {{CYAN}}undertow stop{{reset}}   Stops the currently running Undertow Server
        </description>
        <transform format="text">
            <template style="apon">
                |
                |   {{YELLOW}}Undertow #{tow.server^version} - #{tow.server^state}{{reset}}
                |
            </template>
        </transform>
    </translet>

    <translet name="undertow start">
        <description style="apon">
            |
            |   {{cyan}}Starting the Undertow Server...{{reset}}
            |-----------------------------------------
        </description>
        <action bean="tow.server" method="start"/>
        <transform format="text">
            <template style="apon">
                |
                |   {{YELLOW}}Undertow #{tow.server^version} - #{tow.server^state}{{reset}}
                |   Web server started on localhost:%{tow.server.port}
                |
            </template>
        </transform>
        <exception>
            <thrown type="java.net.BindException">
                <transform format="text">
                    <template style="apon">
                        |
                        |   {{RED}}Undertow Server Error - Port %{tow.server.port} already in use{{reset}}
                        |
                    </template>
                </transform>
            </thrown>
        </exception>
    </translet>

    <translet name="undertow stop">
        <description style="apon">
            |
            |   {{cyan}}Stopping Undertow Server...{{reset}}
            |-----------------------------------------
        </description>
        <action bean="tow.server" method="stop"/>
        <transform format="text">
            <template style="apon">
                |
                |   {{YELLOW}}Undertow #{tow.server^version} - #{tow.server^state}{{reset}}
                |
            </template>
        </transform>
    </translet>

</aspectran>

=== aspectran/aspectran/with-pebble/src/test/resources/config/pebble-test-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran 9.0//EN"
        "https://aspectran.com/dtd/aspectran-9.dtd">
<aspectran>

    <description>
        This is an Aspectran Configuration for Testing.
    </description>

    <settings>
        <setting name="defaultTemplateEngineBean" value="pebble"/>
    </settings>

    <bean id="pebble" class="com.aspectran.pebble.PebbleTemplateEngine">
        <argument>
            <bean class="com.aspectran.pebble.PebbleEngineFactoryBean">
                <property name="templateLoaderPath" type="array">
                    <value>classpath:view</value>
                </property>
                <property name="newLineTrimming" valueType="boolean">false</property>
<!--            <property name="disallowedTokenParserTags" type="set">-->
<!--                <value>include</value>-->
<!--            </property>-->
            </bean>
        </argument>
    </bean>

    <bean id="pebbleViewDispatcher" class="com.aspectran.pebble.view.PebbleViewDispatcher">
        <description>
            Register a Pebble View Dispatcher.
        </description>
        <argument>#{pebble}</argument>
        <property name="suffix">.peb</property>
    </bean>

    <translet name="echo-1">
        <request>
            <parameter name="input_1">${input_1:12345}</parameter>
            <parameter name="input_2">${input_2:67890}</parameter>
        </request>
        <transform format="text">
            <template engine="pebble" style="apon">
                |{{ input_1 }}{{ input_2 }}
            </template>
        </transform>
    </translet>

    <translet name="translet-1">
        <transform format="text">
            <template>~{template-1}</template>
        </transform>
    </translet>

    <translet name="translet-2">
        <dispatch name="template-2" dispatcher="pebbleViewDispatcher"/>
    </translet>

    <template id="template-1" engine="pebble" style="apon">
        |Name: {{ name }}, Email: {{ email }}
    </template>

    <translet name="template-include">
        <dispatch name="template-3" dispatcher="pebbleViewDispatcher"/>
    </translet>

</aspectran>
