=== aspectran/aspectran/core/src/main/resources/com/aspectran/core/context/rule/parser/xml/dtd/aspectran-9.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
  XML DTD for the Aspectran Configuration File, Version 9.0

  Copyright 2018-present The Aspectran Project

  This DTD module is identified by the PUBLIC and SYSTEM identifiers:

  PUBLIC "-//ASPECTRAN//DTD Aspectran 9.0//EN"
  SYSTEM "https://aspectran.com/dtd/aspectran-9.dtd">

  XML documents that conform to this DTD should declare the following doctype:

  <!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran 9.0//EN"
          "https://aspectran.com/dtd/aspectran-9.dtd">
-->

<!ELEMENT aspectran (
  description*,
  settings?,
  (typeAliases | environment | aspect | bean | schedule | translet | template | append)*
)>

<!ELEMENT description (#PCDATA)>
<!ATTLIST description
  profile CDATA #IMPLIED
  style   (apon | compact | compressed) #IMPLIED
>

<!ELEMENT settings (setting+)>
<!ELEMENT setting EMPTY>
<!ATTLIST setting
  name    CDATA #REQUIRED
  value   CDATA #REQUIRED
>

<!ELEMENT typeAliases (typeAlias+)>
<!ELEMENT typeAlias EMPTY>
<!ATTLIST typeAlias
  alias   CDATA #REQUIRED
  type    CDATA #REQUIRED
>

<!ELEMENT environment (description*, property*, properties*)>
<!ATTLIST environment
  profile CDATA #IMPLIED
>

<!ELEMENT aspect (description*, joinpoint?, settings?, advice?, exception?)>
<!ATTLIST aspect
  id       ID #IMPLIED
  order    CDATA #IMPLIED
  isolated (true | false) #IMPLIED
  disabled (true | false) #IMPLIED
>

<!ELEMENT joinpoint (#PCDATA)>
<!ATTLIST joinpoint
  target  (activity | method) #IMPLIED
>

<!ELEMENT advice (before?, after?, finally?)>
<!ATTLIST advice
  bean    CDATA #IMPLIED
>

<!ELEMENT before  (headers | echo | (action | invoke))>
<!ELEMENT after   (headers | echo | (action | invoke))>
<!ELEMENT finally (thrown?, (headers | echo | (action | invoke)))>

<!ELEMENT exception (description*, thrown+)>

<!ELEMENT thrown ((headers | echo | (action | invoke)?)?, (transform | dispatch | redirect)*)>
<!ATTLIST thrown
  type    CDATA #IMPLIED
>

<!ELEMENT bean (description*, filter?, argument*, arguments*, property*, properties*)>
<!ATTLIST bean
  id            CDATA #IMPLIED
  class         CDATA #IMPLIED
  scan          CDATA #IMPLIED
  mask          CDATA #IMPLIED
  factoryBean   CDATA #IMPLIED
  factoryMethod CDATA #IMPLIED
  initMethod    CDATA #IMPLIED
  destroyMethod CDATA #IMPLIED
  dependsOn     CDATA #IMPLIED
  scope         (singleton | prototype | request | session) #IMPLIED
  singleton     (true | false) #IMPLIED
  lazyInit      (true | false) #IMPLIED
  lazyDestroy   (true | false) #IMPLIED
  important     (true | false) #IMPLIED
>

<!ELEMENT filter (#PCDATA)>
<!ATTLIST filter
  class   CDATA #IMPLIED
>

<!ELEMENT schedule (description*, scheduler, job*)>
<!ATTLIST schedule
  id       ID #IMPLIED
  isolated (true | false) #IMPLIED
  disabled (true | false) #IMPLIED
>

<!ELEMENT scheduler (trigger)>
<!ATTLIST scheduler
  bean    CDATA #IMPLIED
>

<!ELEMENT trigger (#PCDATA)>
<!ATTLIST trigger
  type    CDATA #IMPLIED
>

<!ELEMENT job EMPTY>
<!ATTLIST job
  translet CDATA #REQUIRED
  isolated (true | false) #IMPLIED
  disabled (true | false) #IMPLIED
>

<!ELEMENT translet (
  description*,
  (request? | (parameter*, parameters*, attribute*, attributes*)),
  ((contents | content)? | (choose | headers | echo | action | include)*),
  (response* | (transform | dispatch | forward | redirect)?),
  exception?
)>
<!ATTLIST translet
  name    CDATA #REQUIRED
  scan    CDATA #IMPLIED
  mask    CDATA #IMPLIED
  method  CDATA #IMPLIED
  async   (true | false) #IMPLIED
  timeout CDATA #IMPLIED
>

<!ELEMENT request (parameter*, attribute*, parameters*, attributes*)>
<!ATTLIST request
  method   CDATA #IMPLIED
  encoding CDATA #IMPLIED
>

<!ELEMENT contents (content*)>
<!ATTLIST contents
  name    CDATA #IMPLIED
>

<!ELEMENT content (choose | headers | echo | action | include)*>
<!ATTLIST content
  name    CDATA #IMPLIED
>

<!ELEMENT choose (when*, otherwise?)>

<!ELEMENT when ((headers | echo | action | include | choose)*, (transform | dispatch | forward | redirect)?)>
<!ATTLIST when
  test    CDATA #IMPLIED
>

<!ELEMENT otherwise ((headers | echo | action | include | choose)*, (transform | dispatch | forward | redirect)?)>

<!ELEMENT headers (item*)>
<!ATTLIST headers
  id      CDATA #IMPLIED
  hidden  (true | false) #IMPLIED
>

<!ELEMENT echo (item*)>
<!ATTLIST echo
  id      CDATA #IMPLIED
  hidden  (true | false) #IMPLIED
>

<!ELEMENT action (argument*, arguments*, property*, properties*)>
<!ATTLIST action
  id      CDATA #IMPLIED
  bean    CDATA #REQUIRED
  method  CDATA #REQUIRED
  hidden  (true | false) #IMPLIED
>

<!ELEMENT invoke (argument*, arguments*, property*, properties*)>
<!ATTLIST invoke
  method  CDATA #REQUIRED
  hidden  (true | false) #IMPLIED
>

<!ELEMENT include (parameter*, parameters*, attribute*, attributes*)>
<!ATTLIST include
  id       CDATA #IMPLIED
  translet CDATA #REQUIRED
  method   CDATA #IMPLIED
  hidden   (true | false) #IMPLIED
>

<!ELEMENT response ((choose | headers | echo | action | include)*, (transform | dispatch | forward | redirect)?)>
<!ATTLIST response
  name     CDATA #IMPLIED
  encoding CDATA #IMPLIED
>

<!ELEMENT transform (template?)>
<!ATTLIST transform
  format      CDATA #IMPLIED
  contentType CDATA #IMPLIED
  encoding    CDATA #IMPLIED
  default     (true | false) #IMPLIED
  pretty      (true | false) #IMPLIED
>

<!ELEMENT dispatch EMPTY>
<!ATTLIST dispatch
  name        CDATA #REQUIRED
  dispatcher  CDATA #IMPLIED
  contentType CDATA #IMPLIED
  encoding    CDATA #IMPLIED
  default     (true | false) #IMPLIED
>

<!ELEMENT forward (attribute*, attributes*)>
<!ATTLIST forward
  contentType CDATA #IMPLIED
  translet    CDATA #REQUIRED
  method      CDATA #IMPLIED
  default     (true | false) #IMPLIED
>

<!ELEMENT redirect (parameter*, parameters*)>
<!ATTLIST redirect
  contentType            CDATA #IMPLIED
  path                   CDATA #REQUIRED
  encoding               CDATA #IMPLIED
  excludeNullParameters  (true | false) #IMPLIED
  excludeEmptyParameters (true | false) #IMPLIED
  default                (true | false) #IMPLIED
>

<!ELEMENT parameters (item*)>
<!ATTLIST parameters
  profile CDATA #IMPLIED
>

<!ELEMENT attributes (item*)>
<!ATTLIST attributes
  profile CDATA #IMPLIED
>

<!ELEMENT arguments (item*)>
<!ATTLIST arguments
  profile CDATA #IMPLIED
>

<!ELEMENT properties (item*)>
<!ATTLIST properties
  profile CDATA #IMPLIED
>

<!ELEMENT item (#PCDATA | value | entry | bean)*>
<!ATTLIST item
  type      (single | array | list | map | set | properties) #IMPLIED
  name      CDATA #IMPLIED
  value     CDATA #IMPLIED
  valueType (string | int | long | float | double | boolean | parameters | file | multipart-file | bean) #IMPLIED
  tokenize  (true | false) #IMPLIED
  mandatory (true | false) #IMPLIED
  secret    (true | false) #IMPLIED
>

<!ELEMENT parameter (#PCDATA | value | entry | bean)*>
<!ATTLIST parameter
  type      (single | array | list | map | set | properties) #IMPLIED
  name      CDATA #IMPLIED
  value     CDATA #IMPLIED
  valueType (string | int | long | float | double | boolean | parameters | file | multipart-file | bean) #IMPLIED
  tokenize  (true | false) #IMPLIED
  mandatory (true | false) #IMPLIED
  secret    (true | false) #IMPLIED
>

<!ELEMENT attribute (#PCDATA | value | entry | bean)*>
<!ATTLIST attribute
  type      (single | array | list | map | set | properties) #IMPLIED
  name      CDATA #IMPLIED
  value     CDATA #IMPLIED
  valueType (string | int | long | float | double | boolean | parameters | file | multipart-file | bean) #IMPLIED
  tokenize  (true | false) #IMPLIED
  mandatory (true | false) #IMPLIED
  secret    (true | false) #IMPLIED
>

<!ELEMENT argument (#PCDATA | value | entry | bean)*>
<!ATTLIST argument
  type      (single | array | list | map | set | properties) #IMPLIED
  name      CDATA #IMPLIED
  value     CDATA #IMPLIED
  valueType (string | int | long | float | double | boolean | parameters | file | multipart-file | bean) #IMPLIED
  tokenize  (true | false) #IMPLIED
>

<!ELEMENT property (#PCDATA | value | entry | bean)*>
<!ATTLIST property
  type      (single | array | list | map | set | properties) #IMPLIED
  name      CDATA #IMPLIED
  value     CDATA #IMPLIED
  valueType (string | int | long | float | double | boolean | parameters | file | multipart-file | bean) #IMPLIED
  tokenize  (true | false) #IMPLIED
>

<!ELEMENT value (#PCDATA)>

<!ELEMENT entry (#PCDATA | bean)*>
<!ATTLIST entry
  name     CDATA #IMPLIED
  value    CDATA #IMPLIED
  tokenize (true | false) #IMPLIED
>

<!ELEMENT template (#PCDATA)>
<!ATTLIST template
  id          CDATA #IMPLIED
  engine      CDATA #IMPLIED
  name        CDATA #IMPLIED
  file        CDATA #IMPLIED
  resource    CDATA #IMPLIED
  url         CDATA #IMPLIED
  style       (apon | compact | compressed) #IMPLIED
  contentType CDATA #IMPLIED
  encoding    CDATA #IMPLIED
  noCache     (true | false) #IMPLIED
>

<!ELEMENT append (
  description*,
  settings?,
  (typeAliases | environment | aspect | bean | schedule | translet | template)*
)>
<!ATTLIST append
  file     CDATA #IMPLIED
  resource CDATA #IMPLIED
  url      CDATA #IMPLIED
  format   (xml | apon) #IMPLIED
  profile  CDATA #IMPLIED
>

=== aspectran/aspectran/with-jpa/src/test/resources/com/aspectran/jpa/test/jpa-test-context.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran 9.0//EN"
        "https://aspectran.com/dtd/aspectran-9.dtd">
<aspectran>

    <append resource="com/aspectran/jpa/db/db-rules.xml"/>

    <!-- Strict Routing: reuseWritable=false (Must use separate sessions) -->
    <bean id="strictRoutingEntityQuery" class="com.aspectran.jpa.querydsl.EntityQuery">
        <argument>strictTxAspect</argument>
        <argument>strictReadOnlyTxAspect</argument>
        <property name="targetBeanId">strictRoutingEntityQuery</property>
        <property name="entityManagerFactoryBeanId">entityManagerFactory</property>
        <property name="reuseWritable" valueType="boolean">false</property>
    </bean>

    <bean id="strictDao" class="com.aspectran.jpa.test.JpaTestDao">
        <argument>#{strictRoutingEntityQuery}</argument>
    </bean>

    <!-- Intelligent Routing: reuseWritable=true (Reuse writable session if open) -->
    <bean id="intelligentRoutingEntityQuery" class="com.aspectran.jpa.querydsl.EntityQuery">
        <argument>intelligentTxAspect</argument>
        <argument>intelligentReadOnlyTxAspect</argument>
        <property name="targetBeanId">intelligentRoutingEntityQuery</property>
        <property name="entityManagerFactoryBeanId">entityManagerFactory</property>
        <property name="reuseWritable" valueType="boolean">true</property>
    </bean>

    <bean id="intelligentDao" class="com.aspectran.jpa.test.JpaTestDao">
        <argument>#{intelligentRoutingEntityQuery}</argument>
    </bean>

    <!-- Test EntityQuery with single transaction (no routing) -->
    <bean id="singleEntityQuery" class="com.aspectran.jpa.querydsl.EntityQuery">
        <argument>singleTxAspect</argument>
        <property name="targetBeanId">singleEntityQuery</property>
        <property name="entityManagerFactoryBeanId">entityManagerFactory</property>
    </bean>

    <bean id="singleDao" class="com.aspectran.jpa.test.JpaTestDao">
        <argument>#{singleEntityQuery}</argument>
    </bean>

</aspectran>

=== aspectran/aspectran/demo/src/main/resources/com/aspectran/demo/examples/file-upload.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran 9.0//EN"
        "https://aspectran.com/dtd/aspectran-9.dtd">
<aspectran>

    <settings>
        <setting name="transletNamePrefix" value="/examples/file-upload"/>
    </settings>

    <aspect id="transletSettingsForFileUpload">
        <description>
            Specifies the environment variables used during request and response processing.
        </description>
        <joinpoint>
            methods: [
                POST
            ]
            pointcut: {
                +: /examples/file-upload/files
            }
        </joinpoint>
        <settings>
            <!-- Available parsers: standardFileUploader, commonsFileUploader, inMemoryFileUploader -->
            <setting name="multipartFormDataParser" value="standardFileUploader"/>
        </settings>
    </aspect>

    <!-- Standard Jakarta Servlet Multipart Parser (recommended) -->
    <bean id="standardFileUploader"
          class="com.aspectran.web.servlet.support.multipart.standard.StandardServletMultipartFormDataParserFactoryBean">
        <description>
            Handles multipart form data using Jakarta Servlet 3.0+ Part API.
        </description>
        <properties>
            <item name="maxRequestSize" value="10M"/>
            <item name="maxFileSize" value="5M"/>
            <item name="allowedFileExtensions" value="jpg,jpeg,png,gif"/>
        </properties>
    </bean>

    <!-- Apache Commons FileUpload Parser -->
    <bean id="commonsFileUploader"
          class="com.aspectran.web.servlet.support.multipart.commons.CommonsMultipartFormDataParserFactoryBean">
        <description>
            Handles multipart form data using Apache Commons FileUpload.
        </description>
        <properties>
            <item name="maxRequestSize" value="10M"/>
            <item name="maxFileSize" value="5M"/>
            <item name="allowedFileExtensions" value="jpg,jpeg,png,gif"/>
        </properties>
    </bean>

    <!-- In-Memory Multipart Parser -->
    <bean id="inMemoryFileUploader"
          class="com.aspectran.web.servlet.support.multipart.inmemory.InMemoryMultipartFormDataParserFactoryBean">
        <description>
            Handles multipart form data purely in memory without creating temporary files.
        </description>
        <properties>
            <item name="maxRequestSize" value="6M"/>
            <item name="maxFileSize" value="5M"/>
            <item name="allowedFileExtensions" value="jpg,jpeg,png,gif"/>
        </properties>
    </bean>

    <bean class="com.aspectran.demo.examples.upload.SimpleFileUploadActivity">
        <property name="maxFiles" valueType="int">12</property>
    </bean>

    <translet name="/">
        <echo id="page">
            <item name="headline">Uploading Files</item>
            <item name="teaser">
                This guide walks you through the process of creating a server application that can receive
                HTTP multipart file uploads.</item>
            <item name="include">examples/file-upload</item>
            <item name="style">plate</item>
            <item name="maxFiles">#{class:com.aspectran.demo.examples.upload.SimpleFileUploadActivity^maxFiles}</item>
        </echo>
        <action id="files" bean="class:com.aspectran.demo.examples.upload.SimpleFileUploadActivity" method="list"/>
        <dispatch name="templates/default"/>
    </translet>

</aspectran>

=== aspectran/aspectran/embed/src/test/resources/config/aop/simple-aop-test-context.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran 9.0//EN"
        "https://aspectran.com/dtd/aspectran-9.dtd">
<aspectran>

    <description>
        Aspectran's AOP is simple and powerful.
    </description>

    <bean scan="com.aspectran.aop.*TestActivity"/>

    <bean scan="com.aspectran.aop.*TestBean"/>

    <bean scan="com.aspectran.aop.*Aspect"/>

    <bean id="simpleAopTestAdvice" class="com.aspectran.aop.SimpleAopTestAdvice"/>

    <aspect id="aspect01" order="1" disabled="false">
        <joinpoint>
            pointcut: {
                +: aop/test/*
            }
        </joinpoint>
        <advice bean="simpleAopTestAdvice">
            <before>
                <invoke method="begin"/>
            </before>
            <after>
                <invoke method="end"/>
            </after>
            <finally>
                <thrown>
                    <invoke method="thrown"/>
                </thrown>
                <invoke method="close"/>
            </finally>
        </advice>
        <exception>
            <thrown>
                <action bean="simpleAopTestAdvice" method="globalExceptionHandling"/>
            </thrown>
        </exception>
    </aspect>

    <bean id="instantActivityAopTestAdvice" class="com.aspectran.aop.InstantActivityAopTestAdvice"/>

    <aspect id="aspect03" order="1" disabled="false">
        <joinpoint>
            pointcut: {
                +: **@class:com.aspectran.aop.InstantActivityTestBean^begin
            }
        </joinpoint>
        <advice bean="instantActivityAopTestAdvice">
            <before>
                <invoke method="begin"/>
            </before>
            <after>
                <invoke method="end"/>
            </after>
            <finally>
                <thrown>
                    <invoke method="thrown"/>
                </thrown>
                <invoke method="close"/>
            </finally>
        </advice>
        <exception>
            <thrown>
                <action bean="simpleAopTestAdvice" method="globalExceptionHandling"/>
            </thrown>
        </exception>
    </aspect>

</aspectran>

=== aspectran/aspectran/demo/src/main/resources/com/aspectran/demo/terminal/translet-interpreter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran 9.0//EN"
        "https://aspectran.com/dtd/aspectran-9.dtd">
<aspectran>

    <description>
        You can run translets with a command line interpreter implemented using the jQuery Terminal Emulator.
    </description>

    <settings>
        <setting name="transletNamePrefix" value="/interpreter"/>
    </settings>

    <translet name="/">
        <echo id="page">
            <item name="headline">Remote Command Shell</item>
            <item name="teaser">You can run translets with a command line interpreter implemented using the jQuery Terminal Emulator.</item>
            <item name="include">terminal/translet-interpreter</item>
            <item name="style">plate console</item>
        </echo>
        <dispatch name="templates/default"/>
    </translet>

</aspectran>

=== aspectran/aspectran/with-jpa/src/test/resources/com/aspectran/jpa/test/routing/routing-test-context.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran 9.0//EN"
        "https://aspectran.com/dtd/aspectran-9.dtd">
<aspectran>

    <append resource="com/aspectran/jpa/test/db/db-rules.xml"/>

    <!-- Read-Only session: single transaction -->
    <bean id="readOnlyEntityManager" class="com.aspectran.jpa.DefaultEntityManagerAgent">
        <argument>readOnlyTxAspect</argument>
        <property name="targetBeanId">readOnlyEntityManager</property>
        <property name="entityManagerFactoryBeanId">readOnlyEntityManagerFactory</property>
    </bean>

    <bean id="readOnlyDao" class="com.aspectran.jpa.test.routing.dao.JpaTestDao">
        <argument>#{readOnlyEntityManager}</argument>
    </bean>

    <!-- Intelligent Routing: Reuse writable session if open -->
    <bean id="intelligentRoutingEntityManager" class="com.aspectran.jpa.routing.RoutingEntityManagerAgent">
        <argument>intelligentTxAspect</argument>
        <argument>intelligentReadOnlyTxAspect</argument>
        <property name="targetBeanId">intelligentRoutingEntityManager</property>
        <property name="entityManagerFactoryBeanId">entityManagerFactory</property>
    </bean>

    <bean id="intelligentDao" class="com.aspectran.jpa.test.routing.dao.JpaTestDao">
        <argument>#{intelligentRoutingEntityManager}</argument>
    </bean>

    <!-- Test EntityManager with single transaction (no routing) -->
    <bean id="singleEntityManager" class="com.aspectran.jpa.DefaultEntityManagerAgent">
        <argument>singleTxAspect</argument>
        <property name="targetBeanId">singleEntityManager</property>
        <property name="entityManagerFactoryBeanId">entityManagerFactory</property>
    </bean>

    <bean id="singleDao" class="com.aspectran.jpa.test.routing.dao.JpaTestDao">
        <argument>#{singleEntityManager}</argument>
    </bean>

</aspectran>

=== aspectran/aspectran/demo/app/config/server/undertow/tow-context-root.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran 9.0//EN"
        "https://aspectran.com/dtd/aspectran-9.dtd">
<aspectran>

    <description>
        Aspectran configuration for setting up the servlet context.
    </description>

    <environment>
        <property name="tow.context.root.name">root</property>
    </environment>

    <bean id="tow.context.root.servletContext"
          class="com.aspectran.undertow.server.servlet.TowServletContext"
          scope="prototype">
        <property name="deploymentName">%{tow.context.root.name}</property>
        <property name="contextPath">/</property>
        <property name="resourceManager">
            <bean class="com.aspectran.undertow.server.handler.resource.TowResourceManager">
                <property name="base">/webapps/%{tow.context.root.name}</property>
            </bean>
        </property>
        <property name="scratchDir">%{system:aspectran.workPath:/work}/_webapps/%{tow.context.root.name}</property>
        <property name="tempDir">%{system:aspectran.tempPath:/temp}/%{tow.context.root.name}</property>
        <property name="sessionManager">#{tow.context.root.sessionManager}</property>
        <property name="servletSessionConfig">
            <bean class="io.undertow.servlet.api.ServletSessionConfig">
                <!-- Disable URL-based session tracking (no more 'jsessionid' in the URL) -->
                <property name="sessionTrackingModes" type="set">
                    <value>#{class:jakarta.servlet.SessionTrackingMode^COOKIE}</value>
                </property>
                <property name="path" value="/"/>
            </bean>
        </property>
        <property name="servlets" type="array">
            <bean class="com.aspectran.undertow.server.servlet.DefaultJspServlet">
                <property name="loadOnStartup" valueType="int">0</property>
            </bean>
            <bean class="com.aspectran.undertow.server.servlet.TowServlet">
                <argument>webActivityServlet</argument>
                <argument>com.aspectran.web.servlet.WebActivityServlet</argument>
                <property name="mappings" type="array">
                    <value>/</value>
                </property>
                <property name="loadOnStartup" valueType="int">1</property>
                <property name="asyncSupported" valueType="boolean">true</property>
                <property name="multipartConfig">
                    <bean class="jakarta.servlet.MultipartConfigElement">
                        <argument value=""/>
                        <argument valueType="long">10485760</argument>
                        <argument valueType="long">20971520</argument>
                        <argument valueType="int">1048576</argument>
                    </bean>
                </property>
            </bean>
        </property>
        <property name="servletContainerInitializers" type="array">
            <bean class="com.aspectran.undertow.server.servlet.TowJasperInitializer"/>
        </property>
        <property name="webSocketServerContainerInitializer">
            <bean class="com.aspectran.undertow.server.servlet.TowWebSocketServerContainerInitializer">
                <property name="directBuffers" valueType="boolean">true</property>
                <property name="bufferSize" valueType="int">16384</property>
            </bean>
        </property>
    </bean>

    <bean id="tow.context.root.sessionManager"
          class="com.aspectran.undertow.server.session.TowSessionManager"
          scope="prototype">
        <property name="sessionManagerConfig">
            <bean class="com.aspectran.core.context.config.SessionManagerConfig">
                <argument>
                    routeId: %{system:aspectow.node.route}
                    maxActiveSessions: 99
                    maxIdleSeconds: 600
                    evictionIdleSeconds: 300
                    scavengingIntervalSeconds: 180
                    clusterEnabled: false
                </argument>
            </bean>
        </property>
        <properties profile="(!rss-lettuce, !rss-lettuce-primaryreplica, !rss-lettuce-cluster)">
            <item name="sessionStore">
                <bean class="com.aspectran.core.component.session.FileSessionStoreFactoryBean">
                    <properties>
                        <item name="storeDir">%{system:aspectran.workPath:/work}/_sessions/tow</item>
                    </properties>
                </bean>
            </item>
        </properties>
        <properties profile="rss-lettuce">
            <item name="sessionStore">
                <bean class="com.aspectran.core.component.session.redis.lettuce.DefaultLettuceSessionStoreFactoryBean">
                    <properties>
                        <item name="poolConfig">
                            <bean class="com.aspectran.core.component.session.redis.lettuce.RedisConnectionPoolConfig">
                                <properties>
                                    <item name="uri">redis://localhost:6379/0</item>
                                </properties>
                            </bean>
                        </item>
                    </properties>
                </bean>
            </item>
        </properties>
        <properties profile="rss-lettuce-primaryreplica">
            <item name="sessionStore">
                <bean class="com.aspectran.core.component.session.redis.lettuce.DefaultLettuceSessionStoreFactoryBean">
                    <properties>
                        <item name="poolConfig">
                            <bean class="com.aspectran.core.component.session.redis.lettuce.RedisConnectionPoolConfig">
                                <properties>
                                    <item name="uri">redis-sentinel://localhost:11001,localhost:11002,localhost:11003?sentinelMasterId=mymaster</item>
                                </properties>
                            </bean>
                        </item>
                    </properties>
                </bean>
            </item>
        </properties>
        <properties profile="rss-lettuce-cluster">
            <item name="sessionStore">
                <bean class="com.aspectran.core.component.session.redis.lettuce.cluster.ClusterLettuceSessionStoreFactoryBean">
                    <properties>
                        <item name="poolConfig">
                            <bean class="com.aspectran.core.component.session.redis.lettuce.cluster.RedisClusterConnectionPoolConfig">
                                <properties>
                                    <item name="uri">redis://127.0.0.1:6379,127.0.0.1:6380,127.0.0.1:6381</item>
                                </properties>
                            </bean>
                        </item>
                    </properties>
                </bean>
            </item>
        </properties>
    </bean>

</aspectran>
