=== aspectran/aspectran/core/src/main/resources/com/aspectran/core/context/rule/parser/xml/dtd/aspectran-9.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
  XML DTD for the Aspectran Configuration File, Version 9.0

  Copyright 2018-present The Aspectran Project

  This DTD module is identified by the PUBLIC and SYSTEM identifiers:

  PUBLIC "-//ASPECTRAN//DTD Aspectran 9.0//EN"
  SYSTEM "https://aspectran.com/dtd/aspectran-9.dtd">

  XML documents that conform to this DTD should declare the following doctype:

  <!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran 9.0//EN"
          "https://aspectran.com/dtd/aspectran-9.dtd">
-->

<!ELEMENT aspectran (
  description*,
  settings?,
  (typeAliases | environment | aspect | bean | schedule | translet | template | append)*
)>

<!ELEMENT description (#PCDATA)>
<!ATTLIST description
  profile CDATA #IMPLIED
  style   (apon | compact | compressed) #IMPLIED
>

<!ELEMENT settings (setting+)>
<!ELEMENT setting EMPTY>
<!ATTLIST setting
  name    CDATA #REQUIRED
  value   CDATA #REQUIRED
>

<!ELEMENT typeAliases (typeAlias+)>
<!ELEMENT typeAlias EMPTY>
<!ATTLIST typeAlias
  alias   CDATA #REQUIRED
  type    CDATA #REQUIRED
>

<!ELEMENT environment (description*, property*, properties*)>
<!ATTLIST environment
  profile CDATA #IMPLIED
>

<!ELEMENT aspect (description*, joinpoint?, settings?, advice?, exception?)>
<!ATTLIST aspect
  id       ID #IMPLIED
  order    CDATA #IMPLIED
  isolated (true | false) #IMPLIED
  disabled (true | false) #IMPLIED
>

<!ELEMENT joinpoint (#PCDATA)>
<!ATTLIST joinpoint
  target  (activity | method) #IMPLIED
>

<!ELEMENT advice (before?, after?, finally?)>
<!ATTLIST advice
  bean    CDATA #IMPLIED
>

<!ELEMENT before  (headers | echo | (action | invoke))>
<!ELEMENT after   (headers | echo | (action | invoke))>
<!ELEMENT finally (thrown?, (headers | echo | (action | invoke)))>

<!ELEMENT exception (description*, thrown+)>

<!ELEMENT thrown ((headers | echo | (action | invoke)?)?, (transform | dispatch | redirect)*)>
<!ATTLIST thrown
  type    CDATA #IMPLIED
>

<!ELEMENT bean (description*, filter?, argument*, arguments*, property*, properties*)>
<!ATTLIST bean
  id            CDATA #IMPLIED
  class         CDATA #IMPLIED
  scan          CDATA #IMPLIED
  mask          CDATA #IMPLIED
  factoryBean   CDATA #IMPLIED
  factoryMethod CDATA #IMPLIED
  initMethod    CDATA #IMPLIED
  destroyMethod CDATA #IMPLIED
  dependsOn     CDATA #IMPLIED
  scope         (singleton | prototype | request | session) #IMPLIED
  singleton     (true | false) #IMPLIED
  lazyInit      (true | false) #IMPLIED
  lazyDestroy   (true | false) #IMPLIED
  important     (true | false) #IMPLIED
>

<!ELEMENT filter (#PCDATA)>
<!ATTLIST filter
  class   CDATA #IMPLIED
>

<!ELEMENT schedule (description*, scheduler, job*)>
<!ATTLIST schedule
  id       ID #IMPLIED
  isolated (true | false) #IMPLIED
  disabled (true | false) #IMPLIED
>

<!ELEMENT scheduler (trigger)>
<!ATTLIST scheduler
  bean    CDATA #IMPLIED
>

<!ELEMENT trigger (#PCDATA)>
<!ATTLIST trigger
  type    CDATA #IMPLIED
>

<!ELEMENT job EMPTY>
<!ATTLIST job
  translet CDATA #REQUIRED
  isolated (true | false) #IMPLIED
  disabled (true | false) #IMPLIED
>

<!ELEMENT translet (
  description*,
  (request? | (parameter*, parameters*, attribute*, attributes*)),
  ((contents | content)? | (choose | headers | echo | action | include)*),
  (response* | (transform | dispatch | forward | redirect)?),
  exception?
)>
<!ATTLIST translet
  name    CDATA #REQUIRED
  scan    CDATA #IMPLIED
  mask    CDATA #IMPLIED
  method  CDATA #IMPLIED
  async   (true | false) #IMPLIED
  timeout CDATA #IMPLIED
>

<!ELEMENT request (parameter*, attribute*, parameters*, attributes*)>
<!ATTLIST request
  method   CDATA #IMPLIED
  encoding CDATA #IMPLIED
>

<!ELEMENT contents (content*)>
<!ATTLIST contents
  name    CDATA #IMPLIED
>

<!ELEMENT content (choose | headers | echo | action | include)*>
<!ATTLIST content
  name    CDATA #IMPLIED
>

<!ELEMENT choose (when*, otherwise?)>

<!ELEMENT when ((headers | echo | action | include | choose)*, (transform | dispatch | forward | redirect)?)>
<!ATTLIST when
  test    CDATA #IMPLIED
>

<!ELEMENT otherwise ((headers | echo | action | include | choose)*, (transform | dispatch | forward | redirect)?)>

<!ELEMENT headers (item*)>
<!ATTLIST headers
  id      CDATA #IMPLIED
  hidden  (true | false) #IMPLIED
>

<!ELEMENT echo (item*)>
<!ATTLIST echo
  id      CDATA #IMPLIED
  hidden  (true | false) #IMPLIED
>

<!ELEMENT action (argument*, arguments*, property*, properties*)>
<!ATTLIST action
  id      CDATA #IMPLIED
  bean    CDATA #REQUIRED
  method  CDATA #REQUIRED
  hidden  (true | false) #IMPLIED
>

<!ELEMENT invoke (argument*, arguments*, property*, properties*)>
<!ATTLIST invoke
  method  CDATA #REQUIRED
  hidden  (true | false) #IMPLIED
>

<!ELEMENT include (parameter*, parameters*, attribute*, attributes*)>
<!ATTLIST include
  id       CDATA #IMPLIED
  translet CDATA #REQUIRED
  method   CDATA #IMPLIED
  hidden   (true | false) #IMPLIED
>

<!ELEMENT response ((choose | headers | echo | action | include)*, (transform | dispatch | forward | redirect)?)>
<!ATTLIST response
  name     CDATA #IMPLIED
  encoding CDATA #IMPLIED
>

<!ELEMENT transform (template?)>
<!ATTLIST transform
  format      CDATA #IMPLIED
  contentType CDATA #IMPLIED
  encoding    CDATA #IMPLIED
  default     (true | false) #IMPLIED
  pretty      (true | false) #IMPLIED
>

<!ELEMENT dispatch EMPTY>
<!ATTLIST dispatch
  name        CDATA #REQUIRED
  dispatcher  CDATA #IMPLIED
  contentType CDATA #IMPLIED
  encoding    CDATA #IMPLIED
  default     (true | false) #IMPLIED
>

<!ELEMENT forward (attribute*, attributes*)>
<!ATTLIST forward
  contentType CDATA #IMPLIED
  translet    CDATA #REQUIRED
  method      CDATA #IMPLIED
  default     (true | false) #IMPLIED
>

<!ELEMENT redirect (parameter*, parameters*)>
<!ATTLIST redirect
  contentType            CDATA #IMPLIED
  path                   CDATA #REQUIRED
  encoding               CDATA #IMPLIED
  excludeNullParameters  (true | false) #IMPLIED
  excludeEmptyParameters (true | false) #IMPLIED
  default                (true | false) #IMPLIED
>

<!ELEMENT parameters (item*)>
<!ATTLIST parameters
  profile CDATA #IMPLIED
>

<!ELEMENT attributes (item*)>
<!ATTLIST attributes
  profile CDATA #IMPLIED
>

<!ELEMENT arguments (item*)>
<!ATTLIST arguments
  profile CDATA #IMPLIED
>

<!ELEMENT properties (item*)>
<!ATTLIST properties
  profile CDATA #IMPLIED
>

<!ELEMENT item (#PCDATA | value | entry | bean)*>
<!ATTLIST item
  type      (single | array | list | map | set | properties) #IMPLIED
  name      CDATA #IMPLIED
  value     CDATA #IMPLIED
  valueType (string | int | long | float | double | boolean | parameters | file | multipart-file | bean) #IMPLIED
  tokenize  (true | false) #IMPLIED
  mandatory (true | false) #IMPLIED
  secret    (true | false) #IMPLIED
>

<!ELEMENT parameter (#PCDATA | value | entry | bean)*>
<!ATTLIST parameter
  type      (single | array | list | map | set | properties) #IMPLIED
  name      CDATA #IMPLIED
  value     CDATA #IMPLIED
  valueType (string | int | long | float | double | boolean | parameters | file | multipart-file | bean) #IMPLIED
  tokenize  (true | false) #IMPLIED
  mandatory (true | false) #IMPLIED
  secret    (true | false) #IMPLIED
>

<!ELEMENT attribute (#PCDATA | value | entry | bean)*>
<!ATTLIST attribute
  type      (single | array | list | map | set | properties) #IMPLIED
  name      CDATA #IMPLIED
  value     CDATA #IMPLIED
  valueType (string | int | long | float | double | boolean | parameters | file | multipart-file | bean) #IMPLIED
  tokenize  (true | false) #IMPLIED
  mandatory (true | false) #IMPLIED
  secret    (true | false) #IMPLIED
>

<!ELEMENT argument (#PCDATA | value | entry | bean)*>
<!ATTLIST argument
  type      (single | array | list | map | set | properties) #IMPLIED
  name      CDATA #IMPLIED
  value     CDATA #IMPLIED
  valueType (string | int | long | float | double | boolean | parameters | file | multipart-file | bean) #IMPLIED
  tokenize  (true | false) #IMPLIED
>

<!ELEMENT property (#PCDATA | value | entry | bean)*>
<!ATTLIST property
  type      (single | array | list | map | set | properties) #IMPLIED
  name      CDATA #IMPLIED
  value     CDATA #IMPLIED
  valueType (string | int | long | float | double | boolean | parameters | file | multipart-file | bean) #IMPLIED
  tokenize  (true | false) #IMPLIED
>

<!ELEMENT value (#PCDATA)>

<!ELEMENT entry (#PCDATA | bean)*>
<!ATTLIST entry
  name     CDATA #IMPLIED
  value    CDATA #IMPLIED
  tokenize (true | false) #IMPLIED
>

<!ELEMENT template (#PCDATA)>
<!ATTLIST template
  id          CDATA #IMPLIED
  engine      CDATA #IMPLIED
  name        CDATA #IMPLIED
  file        CDATA #IMPLIED
  resource    CDATA #IMPLIED
  url         CDATA #IMPLIED
  style       (apon | compact | compressed) #IMPLIED
  contentType CDATA #IMPLIED
  encoding    CDATA #IMPLIED
  noCache     (true | false) #IMPLIED
>

<!ELEMENT append (
  description*,
  settings?,
  (typeAliases | environment | aspect | bean | schedule | translet | template)*
)>
<!ATTLIST append
  file     CDATA #IMPLIED
  resource CDATA #IMPLIED
  url      CDATA #IMPLIED
  format   (xml | apon) #IMPLIED
  profile  CDATA #IMPLIED
>

=== aspectran/aspectran/core/src/test/resources/config/activity/forward-activity-test-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran 9.0//EN"
        "https://aspectran.com/dtd/aspectran-9.dtd">
<aspectran>

    <bean id="forwardTestHelper" class="com.aspectran.core.activity.ForwardActivityTest$ForwardTestHelper"/>

    <!-- Single Forward Aspects -->
    <aspect id="aspect1" order="1">
        <joinpoint>
            pointcut: {
                +: /step1
            }
        </joinpoint>
        <advice bean="forwardTestHelper">
            <before>
                <invoke method="before1"/>
            </before>
            <after>
                <invoke method="after1"/>
            </after>
            <finally>
                <invoke method="finally1"/>
            </finally>
        </advice>
    </aspect>

    <aspect id="aspect2" order="2">
        <joinpoint>
            pointcut: {
                +: /step2
            }
        </joinpoint>
        <advice bean="forwardTestHelper">
            <before>
                <invoke method="before2"/>
            </before>
            <after>
                <invoke method="after2"/>
            </after>
            <finally>
                <invoke method="finally2"/>
            </finally>
        </advice>
    </aspect>

    <!-- Single Forward Translets -->
    <translet name="/step1">
        <action bean="forwardTestHelper" method="actionStep1"/>
        <forward translet="/step2">
            <attribute name="forwardAttr">forwardVal</attribute>
        </forward>
    </translet>

    <translet name="/step2">
        <action bean="forwardTestHelper" method="actionStep2"/>
        <transform format="text">
            <template>Step 2 completed: @{forwardAttr}</template>
        </transform>
    </translet>

    <!-- Multi Forward Chain Aspects -->
    <aspect id="chainAspect1" order="1">
        <joinpoint>
            pointcut: {
                +: /chain1
            }
        </joinpoint>
        <advice bean="forwardTestHelper">
            <before>
                <invoke method="chainBefore1"/>
            </before>
            <after>
                <invoke method="chainAfter1"/>
            </after>
            <finally>
                <invoke method="chainFinally1"/>
            </finally>
        </advice>
    </aspect>

    <aspect id="chainAspect2" order="2">
        <joinpoint>
            pointcut: {
                +: /chain2
            }
        </joinpoint>
        <advice bean="forwardTestHelper">
            <before>
                <invoke method="chainBefore2"/>
            </before>
            <after>
                <invoke method="chainAfter2"/>
            </after>
            <finally>
                <invoke method="chainFinally2"/>
            </finally>
        </advice>
    </aspect>

    <aspect id="chainAspect3" order="3">
        <joinpoint>
            pointcut: {
                +: /chain3
            }
        </joinpoint>
        <advice bean="forwardTestHelper">
            <before>
                <invoke method="chainBefore3"/>
            </before>
            <after>
                <invoke method="chainAfter3"/>
            </after>
            <finally>
                <invoke method="chainFinally3"/>
            </finally>
        </advice>
    </aspect>

    <!-- Multi Forward Chain Translets -->
    <translet name="/chain1">
        <action bean="forwardTestHelper" method="chainAction1"/>
        <forward translet="/chain2"/>
    </translet>

    <translet name="/chain2">
        <action bean="forwardTestHelper" method="chainAction2"/>
        <forward translet="/chain3"/>
    </translet>

    <translet name="/chain3">
        <action bean="forwardTestHelper" method="chainAction3"/>
        <transform format="text">
            <template>Chain completed</template>
        </transform>
    </translet>

    <!-- Exception Handling Aspects -->
    <aspect id="errorAspect1" order="1">
        <joinpoint>
            pointcut: {
                +: /error-step1
            }
        </joinpoint>
        <advice bean="forwardTestHelper">
            <before>
                <invoke method="errorBefore1"/>
            </before>
            <after>
                <invoke method="errorAfter1"/>
            </after>
            <finally>
                <invoke method="errorFinally1"/>
            </finally>
        </advice>
        <exception>
            <thrown type="java.lang.Exception">
                <action bean="forwardTestHelper" method="errorThrown1"/>
            </thrown>
        </exception>
    </aspect>

    <aspect id="errorAspect2" order="2">
        <joinpoint>
            pointcut: {
                +: /error-step2
            }
        </joinpoint>
        <advice bean="forwardTestHelper">
            <before>
                <invoke method="errorBefore2"/>
            </before>
            <after>
                <invoke method="errorAfter2"/>
            </after>
            <finally>
                <invoke method="errorFinally2"/>
            </finally>
        </advice>
        <exception>
            <thrown type="java.lang.Exception">
                <action bean="forwardTestHelper" method="errorThrown2"/>
            </thrown>
        </exception>
    </aspect>

    <!-- Exception Translets -->
    <translet name="/error-step1">
        <action bean="forwardTestHelper" method="errorAction1"/>
        <forward translet="/error-step2"/>
    </translet>

    <translet name="/error-step2">
        <action bean="forwardTestHelper" method="errorAction2"/>
        <transform format="text">
            <template>Should not reach here</template>
        </transform>
    </translet>

    <!-- ProcessResult Carried Over Translets -->
    <translet name="/data-step1">
        <action id="data1" bean="forwardTestHelper" method="produceData1"/>
        <forward translet="/data-step2"/>
    </translet>

    <translet name="/data-step2">
        <action id="data2" bean="forwardTestHelper" method="produceData2"/>
        <transform format="text">
            <template>@{data1}+@{data2}</template>
        </transform>
    </translet>

</aspectran>

=== aspectran/aspectran/with-undertow/src/test/resources/config/undertow/tow-server.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran 9.0//EN"
        "https://aspectran.com/dtd/aspectran-9.dtd">
<aspectran>

    <description>
        Aspectran configuration for setting up an Undertow server.
    </description>

    <environment>
        <property name="tow.server.startup" valueType="boolean">false</property>
        <property name="tow.server.listener.http.port" valueType="int">%{system:tow.server.listener.http.port:8098}</property>
        <property name="tow.server.listener.http.host">0.0.0.0</property>
    </environment>

    <bean id="tow.server" class="com.aspectran.undertow.server.DefaultTowServer">
        <property name="autoStart">%{tow.server.startup}</property>
        <property name="httpListeners" type="array">
            <bean class="com.aspectran.undertow.server.HttpListenerConfig">
                <property name="port" valueType="int">%{tow.server.listener.http.port}</property>
                <property name="host">%{tow.server.listener.http.host}</property>
            </bean>
        </property>
        <property name="serverOptions">
            <bean class="com.aspectran.undertow.server.TowOptions">
                <property name="decodeUrl" valueType="boolean">true</property>
                <property name="urlCharset">UTF-8</property>
            </bean>
        </property>
        <property name="workerOptions">
            <bean class="com.aspectran.undertow.server.TowOptions">
                <property name="workerName">TOW</property>
            </bean>
        </property>
        <property name="requestHandlerFactory">
            <bean class="com.aspectran.undertow.server.handler.ServletRequestHandlerFactory">
                <property name="servletContexts" type="array">
                    <value>#{tow.context.root.servletContext}</value>
                </property>
                <property name="handlerChainWrappers" type="array">
                    <value>#{tow.server.handler.encodingHandlerWrapper}</value>
                    <value>#{tow.server.handler.accessLogHandlerWrapper}</value>
                </property>
            </bean>
        </property>
    </bean>

    <bean id="tow.server.handler.encodingHandlerWrapper"
          class="com.aspectran.undertow.server.handler.encoding.EncodingHandlerWrapper"
          scope="prototype">
        <property name="encodingProviders" type="array">
            <value>gzip</value>
        </property>
        <property name="encodingPredicates" type="array">
            <bean class="com.aspectran.undertow.server.handler.encoding.ContentEncodingPredicates">
                <property name="mediaTypes" type="array">
                    <value>text/html</value>
                    <value>text/css</value>
                    <value>text/javascript</value>
                    <value>application/javascript</value>
                </property>
            </bean>
            <bean class="com.aspectran.undertow.server.handler.encoding.ContentEncodingPredicates">
                <property name="contentSizeLargerThan" valueType="long">32</property>
                <property name="mediaTypes" type="array">
                    <value>text/xml</value>
                    <value>text/plain</value>
                    <value>application/json</value>
                    <value>application/xml</value>
                    <value>application/apon</value>
                </property>
            </bean>
        </property>
    </bean>

    <bean id="tow.server.handler.accessLogHandlerWrapper"
          class="com.aspectran.undertow.server.handler.accesslog.AccessLogHandlerWrapper"
          scope="prototype">
        <property name="formatString" tokenize="false">%t %a %{i,X-Forwarded-For} %{c,JSESSIONID} "%r" %s %b "%{i,Referer}" "%{i,User-Agent}"</property>
        <property name="category">io.undertow.accesslog</property>
    </bean>

</aspectran>

=== aspectran/aspectran/core/src/test/resources/config/bean/nested-bean-test-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran 9.0//EN"
        "https://aspectran.com/dtd/aspectran-9.dtd">
<aspectran>

    <bean id="stringBean" class="java.lang.String" scope="prototype">
        <argument>String Bean</argument>
    </bean>

    <bean id="mapBean" class="java.util.HashMap" scope="prototype">
        <argument type="map">
            <entry name="item1">value1</entry>
            <entry name="item2">value2</entry>
        </argument>
    </bean>

        <bean id="mapBean2" class="java.util.HashMap" scope="prototype">
            <argument type="map">
                <entry name="ENTRY-1">
                    <bean id="mapBean" class="java.util.ArrayList" scope="prototype">
                        <argument type="list">
                            <bean class="java.lang.String">
                                <argument>ARG-1</argument>
                            </bean>
                            <bean class="java.lang.String">
                                <argument>ARG-2</argument>
                            </bean>
                        </argument>
                    </bean>
                </entry>
            </argument>
        </bean>

    <bean id="listBean" class="java.util.LinkedList" scope="prototype">
        <argument type="list">
            <value>value1</value>
            <value>value2</value>
        </argument>
    </bean>

    <bean id="nestedStringBean" class="java.lang.String" scope="prototype">
        <argument>
            <bean class="java.lang.String">
                <argument>Nested String Bean</argument>
            </bean>
        </argument>
    </bean>

    <bean id="nestedStringBean-1" class="java.lang.String" scope="prototype">
        <argument>
            <bean class="java.lang.String">
                <argument>Nested String Bean</argument>
            </bean>
        </argument>
    </bean>

    <bean id="nestedStringBeanDepth3" class="java.lang.String" scope="prototype">
        <argument>
            <bean class="java.lang.String">
                <argument>
                    <bean class="java.lang.String">
                        <argument>Nested String Bean</argument>
                    </bean>
                </argument>
            </bean>
        </argument>
    </bean>

    <bean id="deepNestedStringBean" class="java.lang.String" scope="prototype">
        <argument>
            <bean class="java.lang.String">
                <argument>
                    <bean class="java.lang.String">
                        <argument>
                            <bean class="java.lang.String">
                                <argument>Nested String Bean</argument>
                            </bean>
                        </argument>
                    </bean>
                </argument>
            </bean>
        </argument>
    </bean>

</aspectran>

=== aspectran/aspectran/core/src/test/resources/com/aspectran/core/scheduler/scheduler-test-context.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran 9.0//EN"
        "https://aspectran.com/dtd/aspectran-9.dtd">
<aspectran>
    <bean id="defaultScheduler" class="com.aspectran.core.scheduler.support.QuartzSchedulerFactoryBean">
        <property type="properties" name="quartzProperties">
            <entry name="org.quartz.scheduler.instanceName">AspectranQuartzScheduler</entry>
            <entry name="org.quartz.threadPool.threadCount">5</entry>
            <entry name="org.quartz.jobStore.class">org.quartz.simpl.RAMJobStore</entry>
        </property>
    </bean>

    <schedule id="test-schedule">
        <scheduler bean="defaultScheduler">
            <trigger type="simple">
                intervalInSeconds: 1
                repeatForever: true
            </trigger>
        </scheduler>
        <job translet="test-job"/>
    </schedule>

    <translet name="test-job">
        <action bean="testBean" method="doWork"/>
    </translet>

    <bean id="testBean" class="com.aspectran.core.scheduler.DistributedSchedulerTest$TestBean"/>

</aspectran>

=== aspectran/aspectran/demo/src/main/resources/com/aspectran/demo/cdn/cdn-assets.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran 9.0//EN"
        "https://aspectran.com/dtd/aspectran-9.dtd">
<aspectran>

    <bean id="cdnAssets" class="com.aspectran.core.support.PropertiesFactoryBean">
        <properties>
            <item name="ignoreInvalidResource" valueType="boolean">false</item>
        </properties>
        <properties profile="prod">
            <item name="locations" type="array">
                <value>classpath:com/aspectran/demo/cdn/cdn-assets-prod.properties</value>
            </item>
        </properties>
        <properties profile="!prod">
            <item name="locations" type="array">
                <value>classpath:com/aspectran/demo/cdn/cdn-assets-dev.properties</value>
            </item>
        </properties>
    </bean>

</aspectran>

=== aspectran/aspectran/with-jetty/src/test/resources/config/server/jetty/jetty-server.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran 9.0//EN"
        "https://aspectran.com/dtd/aspectran-9.dtd">
<aspectran>

    <description>
        Aspectran configuration for setting up a Jetty server.
    </description>

    <environment>
        <property name="jetty.server.startup" value="false" valueType="boolean"/>
        <property name="jetty.server.shutdownGracefully" value="true" valueType="boolean"/>
        <property name="jetty.server.port" value="8099" valueType="int"/>
        <property name="jetty.server.minThreads" value="3" valueType="int"/>
        <property name="jetty.server.maxThreads" value="10" valueType="int"/>
        <property name="jetty.server.maxConnections" value="9999" valueType="int"/>
        <property name="jetty.server.gzip.minGzipSize" value="32" valueType="int"/>
        <property name="jetty.server.gzip.syncFlush" value="false" valueType="boolean"/>
        <property name="jetty.server.gzip.includedMethodList" value="GET,POST"/>
        <property name="jetty.server.gzip.excludedMethodList" value=""/>
    </environment>

    <bean id="jetty.server" class="com.aspectran.jetty.server.JettyServer">
        <argument name="threadPool">
            <bean class="org.eclipse.jetty.util.thread.QueuedThreadPool">
                <property name="minThreads">%{jetty.server.minThreads}</property>
                <property name="maxThreads">%{jetty.server.maxThreads}</property>
            </bean>
        </argument>
        <property name="autoStart">%{jetty.server.startup}</property>
        <property name="shutdownGracefully">%{jetty.server.shutdownGracefully}</property>
        <property name="maxConnections">%{jetty.server.maxConnections}</property>
        <property name="connectors" type="array">
            <value>#{jetty.server.serverConnector}</value>
        </property>
        <property name="handler">
            <value>#{jetty.server.mainHandler}</value>
        </property>
        <property name="requestLog">
            <value>#{jetty.server.requestLog}</value>
        </property>
    </bean>

    <bean id="jetty.server.serverConnector" class="org.eclipse.jetty.server.ServerConnector" scope="prototype">
        <argument>#{jetty.server}</argument>
        <argument type="array">
            <bean class="org.eclipse.jetty.server.HttpConnectionFactory">
                <argument>
                    <bean class="org.eclipse.jetty.server.HttpConfiguration">
                        <property name="customizers" type="list">
                            <bean class="org.eclipse.jetty.server.ForwardedRequestCustomizer"/>
                        </property>
                    </bean>
                </argument>
            </bean>
        </argument>
        <property name="port">%{jetty.server.port}</property>
    </bean>

    <bean id="jetty.server.mainHandler" class="org.eclipse.jetty.server.handler.StatisticsHandler" scope="prototype">
        <argument>
            <bean class="org.eclipse.jetty.server.handler.gzip.GzipHandler">
                <argument>
                    <bean class="org.eclipse.jetty.server.handler.ContextHandlerCollection">
                        <argument valueType="boolean">false</argument>
                        <argument type="array">
                            <value>#{jetty.context.root.webAppContext}</value>
                        </argument>
                    </bean>
                </argument>
                <property name="minGzipSize" valueType="int">%{jetty.server.gzip.minGzipSize}</property>
                <property name="syncFlush" valueType="boolean">%{jetty.server.gzip.syncFlush}</property>
                <property name="includedMethodList">%{jetty.server.gzip.includedMethodList}</property>
                <property name="excludedMethodList">%{jetty.server.gzip.excludedMethodList}</property>
            </bean>
        </argument>
    </bean>

    <bean id="jetty.server.requestLog" class="org.eclipse.jetty.server.CustomRequestLog" scope="prototype">
        <argument>
            <bean class="org.eclipse.jetty.server.Slf4jRequestLogWriter">
                <property name="loggerName">org.eclipse.jetty.server.RequestLog</property>
            </bean>
        </argument>
        <argument tokenize="false">%{yyyy-MM-dd HH:mm:ss.SSS ZZZ|GMT+9}t %{client}a %{X-Forwarded-For}i %{JSESSIONID}C "%r" %s %O "%{Referer}i" "%{User-Agent}i"</argument>
    </bean>

</aspectran>
